# Generated by Django 4.2.2 on 2023-09-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesProducto',
            fields=[
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppGestion.producto')),
                ('marca', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
