# Generated by Django 4.2.2 on 2023-09-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0002_detallesproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallesProducto',
        ),
    ]
